services:
  nats:
    networks: [ frontend ]
    image: "docker.io/library/nats:2.9.17-alpine"
    command: "--config /config/nats/js.conf -m 8222"
    ports:
      - "4222:4222"
      # monitoring port
      - "8222:8222"
    volumes:
      - ./container_files/nats:/config/nats:z
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "http://localhost:8222/healthz"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  guac-collectsub:
    networks: [ frontend ]
    image: $GUAC_IMAGE
    command: "/opt/guac/guaccsub"
    working_dir: /guac
    restart: on-failure
    ports:
      - "2782:2782"
    depends_on:
      nats:
        condition: service_healthy
    volumes:
      - ./container_files/guac:/guac:z
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:2782" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
  guac-graphql:
    container_name: guac-graphql
    networks: 
      - frontend
      - vexgen
    image: $GUAC_IMAGE
    command: "/opt/guac/guacgql"
    working_dir: /guac
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./container_files/guac:/guac:z
    depends_on:
      guac-collectsub:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-O-",
          "http://localhost:8080/healthz"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  frontend:
    container_name: vexgen_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - '3000:3000'
    networks:
      - vexgen

  backend:
    container_name: vexgen_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
      - .env:/backend/.env
    depends_on:
      pypi_graph_database:
        condition: service_healthy
      npm_graph_database:
        condition: service_healthy
      maven_graph_database:
        condition: service_healthy
      cargo_graph_database:
        condition: service_healthy
      nuget_graph_database:
        condition: service_healthy
      vuln_database_seeder:
        condition: service_completed_successfully
    ports:
      - '8000:8000'
    networks:
      - vexgen
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      start_period: 20s

  pypi_graph_database:
    env_file: .env
    container_name: pypi_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_PYPI}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7474
      - NEO4J_server_http_advertised__address=:7474
      - NEO4J_server_bolt_listen__address=:7687
      - NEO4J_server_bolt_advertised__address=:7687
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./seeds/graphs/pypi_neo4j.cypher.gz:/backups/pypi_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  npm_graph_database:
    env_file: .env
    container_name: npm_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_NPM}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7473
      - NEO4J_server_http_advertised__address=:7473
      - NEO4J_server_bolt_listen__address=:7686
      - NEO4J_server_bolt_advertised__address=:7686
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7473:7473'
      - '7686:7686'
    volumes:
      - ./seeds/graphs/npm_neo4j.cypher.gz:/backups/npm_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7473 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  maven_graph_database:
    env_file: .env
    container_name: maven_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_MAVEN}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7472
      - NEO4J_server_http_advertised__address=:7472
      - NEO4J_server_bolt_listen__address=:7685
      - NEO4J_server_bolt_advertised__address=:7685
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7472:7472'
      - '7685:7685'
    volumes:
      - ./seeds/graphs/maven_neo4j.cypher.gz:/backups/maven_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7472 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  cargo_graph_database:
    env_file: .env
    container_name: cargo_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_CARGO}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7471
      - NEO4J_server_http_advertised__address=:7471
      - NEO4J_server_bolt_listen__address=:7684
      - NEO4J_server_bolt_advertised__address=:7684
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7471:7471'
      - '7684:7684'
    volumes:
      - ./seeds/graphs/cargo_neo4j.cypher.gz:/backups/cargo_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7471 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  nuget_graph_database:
    env_file: .env
    container_name: nuget_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_NUGET}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7470
      - NEO4J_server_http_advertised__address=:7470
      - NEO4J_server_bolt_listen__address=:7683
      - NEO4J_server_bolt_advertised__address=:7683
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7470:7470'
      - '7683:7683'
    volumes:
      - ./seeds/graphs/nuget_neo4j.cypher.gz:/backups/nuget_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7470 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  vuln_database_seeder:
    env_file: .env
    container_name: mongodb_seeder
    image: mongo:7.0.11
    depends_on:
      vuln_database:
        condition: service_healthy
    volumes:
      - ./seeds:/seeds
    command:
      /seeds/vulndb_seeder.sh
    networks:
      - vexgen

  vuln_database:
    env_file: .env
    container_name: mongodb
    image: mongo:7.0.11
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${VULN_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${VULN_DB_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - vexgen
    healthcheck:
      test: "echo 'db.stats().ok' | mongosh --username=${VULN_DB_USER} --password=${VULN_DB_PASSWORD} --authenticationDatabase=admin mongodb/testdb"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
networks:
  frontend:
    driver: bridge
  vexgen:
    driver: bridge

volumes:
  blobstore: